@baseUrl=http://localhost:3000
@httpResponse="http-client"

### Find All comments
GET {{baseUrl}}/comments
Accept: application/json

>> comments/get.json
<> comments/get.json

### Find By Id Comment
GET {{baseUrl}}/comments/1
Accept: application/json

>> comments/get-by-id.json
<> comments/get-by-id.json

### Create comments
POST {{baseUrl}}/comments
Accept: application/json
Content-Type: application/json

{
  "text": "New comment"
}

>> comments/post.json
<> comments/post.json


