@baseUrl=http://localhost:3000
@httpResponse="http-client"

### Find All comments
GET {{baseUrl}}/comments
Accept: application/json

>> comments/get.json
<> comments/get.json

### Find all by query param
GET {{baseUrl}}/comments?query=first
Accept: application/json

<> comments/get-query.json

### Find By Id Comment
GET {{baseUrl}}/comments/1
Accept: application/json

>> comments/get-by-id.json
<> comments/get-by-id.json

### Create comments
POST {{baseUrl}}/comments
Accept: application/json
Content-Type: application/json

{
  "text": "New comment"
}

>> comments/post.json
<> comments/post.json

### Update comment
PATCH {{baseUrl}}/comments/3
Accept: application/json
Content-Type: application/json

{
  "text": "Updated Comment"
}

>> comments/patch.json
<> comments/patch.json

### Delete comment
DELETE {{baseUrl}}/comments/3
Accept: application/json

>> comments/delete.json
<> comments/delete.json


### Get Profile
GET {{baseUrl}}/profile/api
Accept: application/json
Authorization: Bearer 123
